// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PaymentsAccount struct {
	ID        uuid.UUID          `json:"id"`
	OwnerID   uuid.UUID          `json:"owner_id"`
	Balance   int64              `json:"balance"`
	Currency  string             `json:"currency"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PaymentsIdempotencyKey struct {
	Key          string             `json:"key"`
	Status       string             `json:"status"`
	ResponseCode pgtype.Int4        `json:"response_code"`
	ResponseBody []byte             `json:"response_body"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LockedAt     pgtype.Timestamptz `json:"locked_at"`
}

type PaymentsTransaction struct {
	ID            uuid.UUID          `json:"id"`
	FromAccountID uuid.UUID          `json:"from_account_id"`
	ToAccountID   uuid.UUID          `json:"to_account_id"`
	Amount        int64              `json:"amount"`
	Currency      string             `json:"currency"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}
