// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createIdempotencyKey = `-- name: CreateIdempotencyKey :one
INSERT INTO payments.idempotency_keys (
    -- lockd_At responde a "hace cuanto esta pasando"
    -- status responde a "que esta pasando"
    key, status, locked_at 
) VALUES (
    $1, $2, NOW()
)
ON CONFLICT (key) DO NOTHING
RETURNING key, status, response_code, response_body, created_at, locked_at
`

type CreateIdempotencyKeyParams struct {
	Key    string `json:"key"`
	Status string `json:"status"`
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (PaymentsIdempotencyKey, error) {
	row := q.db.QueryRow(ctx, createIdempotencyKey, arg.Key, arg.Status)
	var i PaymentsIdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.Status,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.LockedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO payments.transactions (
    from_account_id, 
    to_account_id, 
    amount, 
    currency, 
    status
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, from_account_id, to_account_id, amount, currency, status, created_at
`

type CreateTransactionParams struct {
	FromAccountID uuid.UUID `json:"from_account_id"`
	ToAccountID   uuid.UUID `json:"to_account_id"`
	Amount        int64     `json:"amount"`
	Currency      string    `json:"currency"`
	Status        string    `json:"status"`
}

// Registramos el movimiento inmutable
func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (PaymentsTransaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.Amount,
		arg.Currency,
		arg.Status,
	)
	var i PaymentsTransaction
	err := row.Scan(
		&i.ID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountForRead = `-- name: GetAccountForRead :one
SELECT id, owner_id, balance, currency, created_at, updated_at
FROM payments.accounts
WHERE id = $1
`

// Lectura simple no bloqueante.
func (q *Queries) GetAccountForRead(ctx context.Context, id uuid.UUID) (PaymentsAccount, error) {
	row := q.db.QueryRow(ctx, getAccountForRead, id)
	var i PaymentsAccount
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountForUpdate = `-- name: GetAccountForUpdate :one
SELECT id, owner_id, balance, currency, created_at, updated_at
FROM payments.accounts
WHERE id = $1
FOR NO KEY UPDATE
`

// Bloqueamos la fila para evitar race conditions al modificar el saldo
func (q *Queries) GetAccountForUpdate(ctx context.Context, id uuid.UUID) (PaymentsAccount, error) {
	row := q.db.QueryRow(ctx, getAccountForUpdate, id)
	var i PaymentsAccount
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT key, status, response_code, response_body, created_at, locked_at
FROM payments.idempotency_keys
WHERE key = $1
`

// Buscamos si la clave ya existe para evitar doble procesamiento
func (q *Queries) GetIdempotencyKey(ctx context.Context, key string) (PaymentsIdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, key)
	var i PaymentsIdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.Status,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.LockedAt,
	)
	return i, err
}

const listAccountTransactions = `-- name: ListAccountTransactions :many
SELECT id, from_account_id, to_account_id, amount, currency, status, created_at
FROM payments.transactions
WHERE from_account_id = $1 OR to_account_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAccountTransactionsParams struct {
	FromAccountID uuid.UUID `json:"from_account_id"`
	Limit         int32     `json:"limit"`
	Offset        int32     `json:"offset"`
}

// Listamos las transacciones donde la cuenta es origen o destino, con paginación
func (q *Queries) ListAccountTransactions(ctx context.Context, arg ListAccountTransactionsParams) ([]PaymentsTransaction, error) {
	rows, err := q.db.Query(ctx, listAccountTransactions, arg.FromAccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentsTransaction
	for rows.Next() {
		var i PaymentsTransaction
		if err := rows.Scan(
			&i.ID,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountBalance = `-- name: UpdateAccountBalance :exec
UPDATE payments.accounts
SET balance = balance + $2, 
    updated_at = NOW()
WHERE id = $1
`

type UpdateAccountBalanceParams struct {
	ID      uuid.UUID `json:"id"`
	Balance int64     `json:"balance"`
}

// Actualizamos el saldo y el timestamp
func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error {
	_, err := q.db.Exec(ctx, updateAccountBalance, arg.ID, arg.Balance)
	return err
}

const updateIdempotencyKey = `-- name: UpdateIdempotencyKey :exec
UPDATE payments.idempotency_keys
SET status = $2, 
    response_code = $3, 
    response_body = $4, 
    locked_at = NULL
WHERE key = $1
`

type UpdateIdempotencyKeyParams struct {
	Key          string      `json:"key"`
	Status       string      `json:"status"`
	ResponseCode pgtype.Int4 `json:"response_code"`
	ResponseBody []byte      `json:"response_body"`
}

// Actualizamos el resultado de la operación idempotente
func (q *Queries) UpdateIdempotencyKey(ctx context.Context, arg UpdateIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, updateIdempotencyKey,
		arg.Key,
		arg.Status,
		arg.ResponseCode,
		arg.ResponseBody,
	)
	return err
}
