// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (PaymentsIdempotencyKey, error)
	// Registramos el movimiento inmutable
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (PaymentsTransaction, error)
	// Lectura simple no bloqueante.
	GetAccountForRead(ctx context.Context, id uuid.UUID) (PaymentsAccount, error)
	// Bloqueamos la fila para evitar race conditions al modificar el saldo
	GetAccountForUpdate(ctx context.Context, id uuid.UUID) (PaymentsAccount, error)
	// Buscamos si la clave ya existe para evitar doble procesamiento
	GetIdempotencyKey(ctx context.Context, key string) (PaymentsIdempotencyKey, error)
	// Listamos las transacciones donde la cuenta es origen o destino, con paginación
	ListAccountTransactions(ctx context.Context, arg ListAccountTransactionsParams) ([]PaymentsTransaction, error)
	// Actualizamos el saldo y el timestamp
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error
	// Actualizamos el resultado de la operación idempotente
	UpdateIdempotencyKey(ctx context.Context, arg UpdateIdempotencyKeyParams) error
}

var _ Querier = (*Queries)(nil)
